const productWithDiscription = [
    {
        name: "Foldsack No. 1 Backpack",
        price: 10995,
        category: "men's clothing",
        image: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
    },
    {
        name: "Mens Casual Premium Slim Fit T-Shirts",
        price: 223,
        category: "men's clothing",
        image: "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
    },
    {
        name: "Mens Cotton Jacket",
        price: 5599,
        category: "men's clothing",
        image: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
    },
    {
        name: "Mens Casual Slim Fit",
        price: 1599,
        category: "men's clothing",
        image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
    },
    {
        name: "Silver Dragon Station Chain Bracelet",
        price: 695,
        category: "jewelry",
        image: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
    },
    {
        name: "Solid Gold Petite Micropave",
        price: 168,
        category: "jewelry",
        image: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
    },
    {
        name: "White Gold Plated Princess",
        price: 999,
        category: "jewelry",
        image: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
    },
    {
        name: "Gold Plated Stainless Steel Double",
        price: 1099,
        category: "jewelry",
        image: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
    },
    {
        name: "2TB External Hard Drive",
        price: 640,
        category: "electronics",
        image: "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    },
    {
        name: "SanDisk SSD PLUS 1TB Internal SSD",
        price: 199,
        category: "electronics",
        image: "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    },
    {
        name: "Silicon Power 256GB SSD",
        price: 109,
        category: "electronics",
        image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    },
    {
        name: "WD 4TB Gaming Drive",
        price: 114,
        category: "electronics",
        image: "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    },
    {
        name: "21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
        price: 599,
        category: "electronics",
        image: "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    },
    {
        name: "Samsung 49-Inch Gaming Monitor",
        price: 9999,
        category: "electronics",
        image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    },
    {
        name: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
        price: 5699,
        category: "women's clothing",
        image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
    },
    {
        name: "Removable Hooded Faux Leather Moto Biker Jacket",
        price: 2995,
        category: "women's clothing",
        image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
    },
    {
        name: "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
        price: 3999,
        category: "women's clothing",
        image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
    },
    {
        name: "MBJ Women's Solid Short Sleeve Boat Neck V",
        price: 985,
        category: "women's clothing",
        image: "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
    },
    {
        name: "Opna Women's Short Sleeve Moisture",
        price: 795,
        category: "women's clothing",
        image: "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
    },
    {
        name: "DANVOUY Womens T Shirt Casual Cotton Short",
        price: 1299,
        category: "women's clothing",
        image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
    },
    {
        name: "iPhone 9",
        price: 5490,
        category: "smartphones",
        image: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    },
    {
        name: "iPhone X",
        price: 8990,
        category: "smartphones",
        image: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    },
    {
        name: "Samsung Universe 9",
        price: 12490,
        category: "smartphones",
        image: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    },
    {
        name: "OPPOF19",
        price: 2800,
        category: "smartphones",
        image: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    },
    {
        name: "Huawei P30",
        price: 4990,
        category: "smartphones",
        image: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    },
    {
        name: "MacBook Pro",
        price: 17490,
        category: "laptops",
        image: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    },
    {
        name: "Samsung Galaxy Book",
        price: 8499,
        category: "laptops",
        image: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    },
    {
        name: "Microsoft Surface Laptop 4",
        price: 44990,
        category: "laptops",
        image: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    },
    {
        name: "Infinix INBOOK",
        price: 40099,
        category: "laptops",
        image: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    },
    {
        name: "HP Pavilion 15-DK1056WM",
        price: 10099,
        category: "laptops",
        image: "https://i.dummyjson.com/data/products/10/2.jpg",
    },
    {
        name: "perfume Oil",
        price: 1300,
        category: "fragrances",
        image: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    },
    {
        name: "Brown Perfume",
        price: 4000,
        category: "fragrances",
        image: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    },
    {
        name: "Fog Scent Xpressio Perfume",
        price: 1300,
        category: "fragrances",
        image: "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    },
    {
        name: "Non-Alcoholic Concentrated Perfume Oil",
        price: 1200,
        category: "fragrances",
        image: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    },
    {
        name: "Eau De Perfume Spray",
        price: 3000,
        category: "fragrances",
        image: "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    },
    {
        name: "Hyaluronic Acid Serum",
        price: 1900,
        category: "skincare",
        image: "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    },
    {
        name: "Tree Oil 30ml",
        price: 1200,
        category: "skincare",
        image: "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
    },
    {
        name: "Oil Free Moisturizer 100ml",
        price: 4000,
        category: "skincare",
        image: "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    },
    {
        name: "Skin Beauty Serum",
        price: 4600,
        category: "skincare",
        image: "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
    },
    {
        name: "Freckle Treatment Cream- 15gm",
        price: 7000,
        category: "skincare",
        image: "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
    },
    {
        name: "Daal Masoor 500 grams",
        price: 350,
        category: "groceries",
        image: "https://i.dummyjson.com/data/products/21/thumbnail.png",
    },
    {
        name: "Elbow Macaroni - 400 gm",
        price: 140,
        category: "groceries",
        image: "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
    },
    {
        name: "Orange Essence Food Flavou",
        price: 140,
        category: "groceries",
        image: "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
    },
    {
        name: "cereals muesli fruit nuts",
        price: 460,
        category: "groceries",
        image: "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
    },
    {
        name: "Gulab Powder 50 Gram",
        price: 700,
        category: "groceries",
        image: "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
    },
    {
        name: "Plant Hanger For Home",
        price: 410,
        category: "home-decoration",
        image: "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
    },
    {
        name: "Flying Wooden Bird",
        price: 510,
        category: "home-decoration",
        image: "https://i.dummyjson.com/data/products/27/thumbnail.webp",
    },
    {
        name: "3D Embellishment Art Lamp",
        price: 200,
        category: "home-decoration",
        image: "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
    },
    {
        name: "Handcraft Chinese style",
        price: 600,
        category: "home-decoration",
        image: "https://i.dummyjson.com/data/products/29/2.jpg",
    },
    {
        name: "Key Holder",
        price: 300,
        category: "home-decoration",
        image: "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
    }
]